"""create document text table

Revision ID: 1d95b92a5cbe
Revises: b0052038fe0f
Create Date: 2026-07-07 16:36:05.463528
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1d95b92a5cbe'
down_revision: str | None = 'b0052038fe0f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_text',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_text_document_id'), 'document_text', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_text_document_id'), table_name='document_text')
    op.drop_table('document_text')
    # ### end Alembic commands ###
