"""create entity tags table

Revision ID: 2f87fa78044a
Revises: 9dc95a57a27b
Create Date: 2026-07-07 13:34:02.768842
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2f87fa78044a'
down_revision: str | None = '9dc95a57a27b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'tag_id', name='uq_entity_tags_entity_id_tag_id')
    )
    op.create_index(op.f('ix_entity_tags_entity_id'), 'entity_tags', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_tags_tag_id'), 'entity_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_tags_tag_id'), table_name='entity_tags')
    op.drop_index(op.f('ix_entity_tags_entity_id'), table_name='entity_tags')
    op.drop_table('entity_tags')
    # ### end Alembic commands ###
