"""create relationships table

Revision ID: 731af1e15e83
Revises: 2b1474dc69d1
Create Date: 2026-07-06 22:53:45.029130
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '731af1e15e83'
down_revision: str | None = '2b1474dc69d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_relationship_type'), 'relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_relationships_source_entity_id'), 'relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_entity_id'), 'relationships', ['target_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_target_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_relationship_type'), table_name='relationships')
    op.drop_table('relationships')
    # ### end Alembic commands ###
