"""add pgvector embedding columns

Revision ID: 7ec30ec2782d
Revises: ba809fc7516b
Create Date: 2026-07-07 18:45:43.931275
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '7ec30ec2782d'
down_revision: str | None = 'ba809fc7516b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_embeddings', sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=16), nullable=True))
    op.add_column('document_embeddings', sa.Column('metadata_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_embeddings', 'metadata_json')
    op.drop_column('document_embeddings', 'embedding_vector')
    # ### end Alembic commands ###
