"""create tags table

Revision ID: 9dc95a57a27b
Revises: f89f3056b8cc
Create Date: 2026-07-07 12:36:14.187520
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9dc95a57a27b'
down_revision: str | None = 'f89f3056b8cc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
