"""create document embeddings table

Revision ID: ba809fc7516b
Revises: 0ccd4f96065a
Create Date: 2026-07-07 18:03:21.788277
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ba809fc7516b'
down_revision: str | None = '0ccd4f96065a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
