"""create document chunks table

Revision ID: c5b5661878d8
Revises: 1d95b92a5cbe
Create Date: 2026-07-07 17:09:02.256922
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c5b5661878d8'
down_revision: str | None = '1d95b92a5cbe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_text_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_text_id'], ['document_text.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_text_id'), 'document_chunks', ['document_text_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_document_text_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
