"""create tags table

Revision ID: f89f3056b8cc
Revises: c810da0c8081
Create Date: 2026-07-07 12:32:01.581287
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f89f3056b8cc'
down_revision: str | None = 'c810da0c8081'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
